/* tslint:disable */
/* eslint-disable */
/**
 * Fetcher API
 * Fetch social media feeds
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FeedItems,
} from '../models/index';

export interface GetFeedRequest {
    twitterID?: number;
    instagramID?: number;
    bloggerID?: string;
    soundcloudID?: string;
    swarmID?: string;
    deviantartID?: string;
    untappdID?: string;
    blueskyID?: string;
}

export interface ProxyRequest {
    url?: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates request options for getFeed without sending the request
     */
    async getFeedRequestOpts(requestParameters: GetFeedRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['twitterID'] != null) {
            queryParameters['twitterID'] = requestParameters['twitterID'];
        }

        if (requestParameters['instagramID'] != null) {
            queryParameters['instagramID'] = requestParameters['instagramID'];
        }

        if (requestParameters['bloggerID'] != null) {
            queryParameters['bloggerID'] = requestParameters['bloggerID'];
        }

        if (requestParameters['soundcloudID'] != null) {
            queryParameters['soundcloudID'] = requestParameters['soundcloudID'];
        }

        if (requestParameters['swarmID'] != null) {
            queryParameters['swarmID'] = requestParameters['swarmID'];
        }

        if (requestParameters['deviantartID'] != null) {
            queryParameters['deviantartID'] = requestParameters['deviantartID'];
        }

        if (requestParameters['untappdID'] != null) {
            queryParameters['untappdID'] = requestParameters['untappdID'];
        }

        if (requestParameters['blueskyID'] != null) {
            queryParameters['blueskyID'] = requestParameters['blueskyID'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/feed`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get feed.
     * Get feed
     */
    async getFeedRaw(requestParameters: GetFeedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FeedItems>> {
        const requestOptions = await this.getFeedRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get feed.
     * Get feed
     */
    async getFeed(requestParameters: GetFeedRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FeedItems> {
        const response = await this.getFeedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for proxy without sending the request
     */
    async proxyRequestOpts(requestParameters: ProxyRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['url'] != null) {
            queryParameters['url'] = requestParameters['url'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/proxy`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Proxy url.
     * Proxy url
     */
    async proxyRaw(requestParameters: ProxyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.proxyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Proxy url.
     * Proxy url
     */
    async proxy(requestParameters: ProxyRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.proxyRaw(requestParameters, initOverrides);
    }

}
