/*
 * Fetcher
 *
 * Fetch social media feeds
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package fetcher

//Implementation response defines an error code with the associated body
type ImplResponse struct {
	Code int
	Body interface{}
}
