/*
 * Fetcher
 *
 * Fetch social media feeds
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package fetcher

type FeedItemMedia struct {

	// The URL to the media content
	Url string `json:"url"`

	// The URL to a poster image
	Poster string `json:"poster,omitempty"`

	// The kind of media
	Kind string `json:"kind"`
}
