/*
 * jessemichael.me internal
 *
 * Internal workings of Jesse Michael
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package fetcher

type FeedItem struct {

	Id string `json:"id"`

	Date string `json:"date"`

	Source string `json:"source"`

	Link string `json:"link,omitempty"`

	Media string `json:"media,omitempty"`

	Content string `json:"content,omitempty"`
}
