/*
 * Fetcher
 *
 * Fetch social media feeds
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package fetcher

type FeedItems struct {

	Items []FeedItem `json:"items"`
}
