/**
 * Fetcher
 * Fetch social media feeds
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FeedItemMedia } from './feedItemMedia';

export class FeedItem {
    /**
    * Unique identifier for a feed item
    */
    'id': string;
    /**
    * Unix timestamp (seconds) for when the item was published
    */
    'ts': number;
    /**
    * The source platform the item is from
    */
    'source': FeedItem.SourceEnum;
    /**
    * Permalink to the feed item on the platform
    */
    'url'?: string;
    /**
    * Array of media items (images, videos, etc...)
    */
    'media'?: Array<FeedItemMedia>;
    /**
    * Text content for the item (may contain HTML)
    */
    'content'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "ts",
            "baseName": "ts",
            "type": "number"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "FeedItem.SourceEnum"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "media",
            "baseName": "media",
            "type": "Array<FeedItemMedia>"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FeedItem.attributeTypeMap;
    }
}

export namespace FeedItem {
    export enum SourceEnum {
        Twitter = <any> 'twitter',
        Instagram = <any> 'instagram',
        Blogger = <any> 'blogger',
        Soundcloud = <any> 'soundcloud',
        Swarm = <any> 'swarm',
        Deviantart = <any> 'deviantart'
    }
}
