/**
 * Fetcher
 * Fetch social media feeds
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class FeedItem {
    /**
    * Unique identifier for a feed item
    */
    'id': string;
    /**
    * Unix timestamp (seconds) for when the item was published
    */
    'ts': number;
    /**
    * The source platform the item is from
    */
    'source': FeedItem.SourceEnum;
    /**
    * Permalink to the feed item on the platform
    */
    'url'?: string;
    /**
    * URL to media (image, video, etc..)
    */
    'media'?: string;
    /**
    * Text content for the item
    */
    'content'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "ts",
            "baseName": "ts",
            "type": "number"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "FeedItem.SourceEnum"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "media",
            "baseName": "media",
            "type": "string"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FeedItem.attributeTypeMap;
    }
}

export namespace FeedItem {
    export enum SourceEnum {
        Twitter = <any> 'twitter'
    }
}
