/*
 * jessemichael.me internal
 *
 * Internal workings of Jesse Michael
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	"github.com/dghubble/go-twitter/twitter"
	fetcher "github.com/jesse0michael/fetcher/pkg/fetcher"
	"golang.org/x/oauth2"
	"golang.org/x/oauth2/clientcredentials"
)

func main() {
	log.Printf("Server started")

	// oauth2 configures a client that uses app credentials to keep a fresh token
	config := &clientcredentials.Config{
		ClientID:     "tswH7DBOa2WbGMMBUasl8g",
		ClientSecret: "htau31s5eKenDHP0e3gPbVq1krXC6kQxzvXsp20ls0",
		TokenURL:     "https://api.twitter.com/oauth2/token",
	}
	// http.Client will automatically authorize Requests
	httpClient := config.Client(oauth2.NoContext)

	// Twitter client
	twitterClient := twitter.NewClient(httpClient)

	DefaultAPIService := fetcher.NewDefaultApiService(twitterClient)
	DefaultAPIController := fetcher.NewDefaultApiController(DefaultAPIService)

	router := fetcher.NewRouter(DefaultAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
