name: Release Workflow
on:
  release:
    types: [published]

jobs:
  release:
    env:
      REF: ${{ github.ref }}
    name: Release Fetcher
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate into Google Cloud Platform
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_email: ${{ secrets.GCLOUD_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Configure Docker to use Google Cloud Platform
        run: "gcloud auth configure-docker --quiet"

      - name: Build
        run: |
          docker build \
            --file ./build/Dockerfile \
            -t docker.pkg.github.com/jesse0michael/fetcher/api:${REF##*/} \
            -t us-west1.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}:${REF##*/} .

      - name: Push Images
        run: |
          docker login docker.pkg.github.com -u Jesse0Michael -p ${{ secrets.PAT }}
          docker push docker.pkg.github.com/jesse0michael/fetcher/api:${REF##*/}
          docker push us-west1.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}:${REF##*/}

  release-client:
    env:
      REF: ${{ github.ref }}
    name: Release Node Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@jesse0michael"

      - name: Build Client
        working-directory: client/ts
        run: |
          npm install
          npm run build

      - name: Publish Client
        working-directory: client/ts
        run: |
          npm config set //npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN
          npm config set scope "jesse0michael"
          npm version ${REF##*/}
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}
