name: Release Workflow
on:
  push:
    tags:
      - "*"

jobs:
  release:
    env:
      REF: ${{ github.ref }}
    name: Release Fetcher
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          docker build \
            -t docker.pkg.github.com/jesse0michael/Fetcher/fetcher:${REF##*/} \
            -t registry.heroku.com/uuid-farm/web .

      - name: Publish Server
        run: |
          docker login docker.pkg.github.com -u Jesse0Michael -p ${{ secrets.GITHUB_SECRET }}
          docker push docker.pkg.github.com/jesse0michael/uuid-farm/uuid-farm:${REF##*/}

  release-client:
    env:
      REF: ${{ github.ref }}
    name: Release Node Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@jesse0michael"

      - name: Build Client
        working-directory: client/ts
        run: |
          npm install
          npm run build

      - name: Publish Client
        working-directory: client/ts
        run: |
          npm config set //npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN
          npm config set scope "jesse0michael"
          npm version ${REF##*/}
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_SECRET }}

  release-frontend:
    name: Release Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@jesse0michael"

      - name: Build Frontend
        working-directory: ui
        run: |
          npm install
          npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_SECRET }}

      - name: Deploy Frontend
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ui
