name: Release Workflow
on:
  release:
    types: [published]

jobs:
  release:
    env:
      REF: ${{ github.ref }}
    name: Release Fetcher
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCLOUD_AUTH }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Docker Auth
        run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          docker build \
            --file ./build/Dockerfile \
            -t docker.pkg.github.com/jesse0michael/fetcher/api:${REF##*/} \
            -t us.gcr.io/${{ steps.auth.outputs.project_id }}/fetcher:${REF##*/} .

      - name: Push Images
        run: |
          docker login docker.pkg.github.com -u Jesse0Michael -p ${{ secrets.PAT }}
          docker push docker.pkg.github.com/jesse0michael/fetcher/api:${REF##*/}

          docker push us.gcr.io/${{ steps.auth.outputs.project_id }}/fetcher:${REF##*/}

  release-client:
    env:
      REF: ${{ github.ref }}
    name: Release Node Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          scope: "@jesse0michael"

      - name: Regenerate Client
        run: make gen

      - name: Publish to npm
        working-directory: client/ts
        run: |
          npm install
          npm version ${REF##*/}
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to GitHub Packages
        working-directory: client/ts
        run: |
          npm config set //npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN
          npm config set scope "jesse0michael"
          npm config set registry https://npm.pkg.github.com/
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}
